<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SignalCpf.Protocol</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSec.Cryptography" Version="24.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SignalCpf.Protobuf\SignalCpf.Protobuf.csproj" />
  </ItemGroup>
</Project>
